sudo: false
language: node_js
node_js:
  - '6'
  - '7'
  - '8'
install:
  - npm i
script:
  - npm run build
  - npm run test
# after_script:
#   - npminstall codecov && codecov
#   - scripts/doc_travis.sh
env:
  global:
  - ENCRYPTION_LABEL: a62186272189
